We thank the reviewers for their helpful feedback and insightful
questions. In the revision, we plan to clarify the novelty of our
contribution over prior work and discuss the relationship to the
existing work on gradual typing and algebraic effects, in particular,
the work of New et al. on GrEff (cited as [23] in the paper).

Below we address specific points from the reviews:

* *Relationship with prior work on graduality for algebraic effects*

  There are two distinct but related questions involving the
  relationship with prior work on gradual typing for algebraic
  effects. Specifically, could we accommodate effect handlers, and how
  do we relate to the work of New et al. on GrEff ([23] in the paper).

  The framework in our paper gives a language with a fixed global
  notion of effect given by an algebraic theory. Languages with effect
  handlers can be modeled as using effects given by free theories
  (those with no equations). If you were to fix a global effect
  signature, our framework would accommodate effect handlers; we would
  only have to add a new handler form to the language and extend our
  denotational semantics and logical relation with some easy cases to
  extend the result. From this perspective, our work is more general
  than just effect handlers because we also model effects like state
  that require equations.

  Many calculi with effect handlers allow for *effect typing* where
  different portions of the code are given types corresponding to
  different effect signatures, so that a programmer can reason about
  which effects can be raised and prove that all effects are
  handled. This would not fit into our framework since it changes the
  language design at a more fundamental level, but it could be easily
  accommodated, as long as the gradual typing is only over ordinary
  value types rather than effect types.

  GrEff supports *gradual* effect typing, which means that there is a
  dynamic effect and semantically there are casts between effects. We
  expect our approach to generalize to handle this feature, but it is
  a more significant extension to the current work than just adding
  support for effect handlers.

* *Agda mechanization*

  Reviewers A and C mention the absence of an Agda mechanization and
  ask about challenges to mechanizing our results. We are confident
  that it is possible to extend the Agda development of Giovannini et
  al. with our results; the primary obstacle is the extensive time and
  labor required. More concretely, aspects that would need to be built
  from scratch include:

  - the syntax and small-step operational semantics and proofs that
    the semantics satisfies the usual progress, preservation, and
    determinism properties
  - the definition of the logical relation for adequacy and proof of
    associated lemmas
  - the proofs of the compatibility lemmas for the logical relation
  - the definition of guarded algebraic theories and operations on
    theories
  - the notion of $\mathcal{A}_{\mho s}$-domains for an algebraic
    theory $\mathcal{A}$, as well as a construction of the adjunction
    between the (double) category of predomains and $\mathcal{A}_{\mho
    s}$-domains
  - notions of player and opponent traces and the orderings on traces
  - a globalization construction on the free algebras of a free
    theory, that is, a map from the guarded free algebras into
    coinductive interaction trees
  - "transformer theorems" relating the theory transformers we support
    to transformers of graduality schemata

  In all, our estimation is that this work, if carried out in full,
  would be roughly on the scale of the entire existing mechanization
  of Giovannini et al.

* *Broader lessons on gradual typing and/or algebraic effects*

  Reviewer B asks what the combined framework teaches us about either
  gradual typing or algebraic effects. Our work contributes the next
  important step towards a systematic theory of gradual typing for
  languages with real world, advanced features. Our contribution to
  this is to bring the systematic denotational approach of prior work
  to operational graduality as well as extending the denotational
  approach to handle algebraic effects. The fact that the resulting
  combination works straightforwardly is a consequence of designing
  the correct abstractions, which is where the hard work lies.

* *Guarded operations besides $θ$*

  Reviewers B and C ask if the only intended example of operations
  with guarded arities is $θ$. The primary reason we use this
  generality is that we consider two distinct $θ$ operations (one for
  "true" steps, and one for "bureaucratic steps"). The notion of
  guarded arity allows us to cleanly abstract over both of these
  operations in our proofs.

* *Why no infinite arities?*

  Reviewer C asks whether we could extend our framework to allow for
  infinitary effects. We believe this is possible in principle, but
  there are a few steps we would need to take to extend existing
  results. First we would need to modify the cast calculus syntax, in
  a way similar to Kavvos [1], who defines a notion of first-order
  universe and establishes an isomorphism between a syntactic universe
  of values (used within the object language) and a semantic universe
  of values (used for the meta-level arity types). Second, we would
  need to ensure that the globalization result for the free algebras
  of free theories continues to hold. For finitary theories, we used a
  result of Møgelberg and Zwart [2] (see their Proposition 3.4). We
  would need to extend result to infinitary theories, but we believe
  that this holds.

* *Partiality as an effect*

  Reviewer C asks whether our framework could handle recursive
  definitions by modeling partiality as an effect. Indeed, guarded
  type theory is the algebraic way of talking about the delay monad;
  the explicit connection is made via the notion of *globalization*
  [3]. In particular, when we globalize the free-algebras for a free
  theory, the result is a coinductive interaction tree; with no
  operations besides θ, this results in the usual delay monad.

  Guarded type theory provides a nice setting in which to perform
  coinductive reasoning without worrying about the syntactic
  restrictions of coinductive definitions in proof assistants. In this
  sense, we believe that the delay monad and other coinductive
  definitions are best understood in terms of guarded type theory.


[1]: G. A. Kavvos. Adequacy for Algebraic Effects Revisited. OOPSLA 2025. https://doi.org/10.1145/3720457

[2]: Rasmus Ejlers Møgelberg and Maaike Zwart. What Monads Can and Cannot Do with a Few Extra Pages. Logical Methods in Computer Science. https://lmcs.episciences.org/16664

[3]: Robert Atkey and Conor McBride. Productive Coprogramming with Guarded Recursion. ICFP 2013. https://doi.org/10.1145/2500365.2500597
